version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: "${PRISMA_PORT}"
        databases:
          default:
            connector: postgres
            host: postgres
            port: "${DB_PORT}"
            user: "${DB_USER}"
            password: "${DB_PASSWORD}"
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
